name: CONDITION-TEMPLATES
on:
  workflow_dispatch:
    inputs:
      product:
        description: 'Product name'
        required: true
        type: string
      template:
        description: 'Template name'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  ACTOR: sige3-desarrollo
  IMAGE_APP_NAME: sigevih
  APP_NAME: back-public
  EKS_CLUSTER_NAME: my-cluster
  AWS_REGION: us-east-1
  N_REPLICA: 2

jobs:
  build_contenizer:
    name: Build & Contenerize App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "$PRODUCT"
          echo "$TEMPLATE"
