name: CONDITION-TEMPLATES
on:
  workflow_dispatch:
    inputs:
      product:
        description: 'Product name'
        required: true
        type: string
      template:
        description: 'Template name'
        required: true
        type: string

jobs:
  build_contenizer:
    name: Build & Contenerize App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: log inputs
        env:
          PRODUCT: ${{ inputs.product }}
          TEMPLATE: ${{ inputs.template }}
        run: |
          echo "$PRODUCT"
          echo "$TEMPLATE"
