name: CONDITION-TEMPLATES
on:
  workflow_dispatch:
    inputs:
      product:
        description: 'Product name'
        required: true
        type: string
      template:
        description: 'Template name'
        required: true
        type: string

env:
  PRODUCT: ${{ inputs.product }}
  TEMPLATE: ${{ inputs.template }}

jobs:
  build_contenizer:
    name: Build & Contenerize App
    runs-on: ubuntu-latest

    steps:
      - name: Log inputs
        run: |
          echo "$PRODUCT"
          echo "$TEMPLATE"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: dmn

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: saman-core/condition-template
          path: condition-template

      - name: Copy files
        run: |
          ls dmn
          ls condition-template
          cp dmn/$(echo $PRODUCT)/templates/$(echo $TEMPLATE)/conditions/* condition-template/src/main/resources/
          ls condition-template/src/main/resources/

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'mandrel'
          github-token: ${{ secrets.GIT_TOKEN }}
          native-image-job-reports: 'true'
          version: '22.3.3.1-Final'

      - name: Build native app
        run: |
          ./mvnw package -Dnative -Dquarkus.profile=quality -DskipTests
