name: FIND-CHANGES
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  build_contenizer:
    name: Build & Contenerize App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set env
        run: |
          PRODUCT="auto"
          TEMPLATE="auto_a"
          gh workflow run ci-cd-conditions.yml --repo saman-core/condition-template --ref main -f product=$(echo $PRODUCT) -f template=$(echo $TEMPLATE)
