name: OBSERVER-CHANGES
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GIT_TOKEN }}
  EKS_CLUSTER_NAME: my-cluster
  AWS_REGION: us-east-1

jobs:
  listener:
    name: Observer Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Find Conditions
        run: |
          GIT_ACTUAL_HASH=$(git rev-parse HEAD)
          for path in $(find . -name form.json); do
            PRODUCT=$(echo "$path" | cut -d "/" -f2);
            TEMPLATE=$(echo "$path" | cut -d "/" -f4);
            GIT_DEPLOY_HASH=$(kubectl get deployment conditions-$(echo $PRODUCT)-$(echo $TEMPLATE) -n api -o jsonpath='{.metadata.annotations.deployHash}')
            
            GIT_DIFF=$(git diff $(echo $GIT_DEPLOY_HASH) $(echo $GIT_ACTUAL_HASH) --name-only -- $(echo $PRODUCT)/templates/$(echo $TEMPLATE)/conditions)
            echo "$GIT_DIFF"
          done
